[project]
name = "pyscript"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "cx-oracle>=8.3.0",
    "pillow>=11.3.0",
    "tqdm>=4.67.1",
]
